name: Terraform check

on: 
  push:
  

jobs:
  Terraform-check:
    name: Terraform-CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout respository
      uses: actions/checkout@v3

    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - uses: terraform-linters/setup-tflint@v3
      with: 
        tflint_version: latest 

    - name: Show version 
      run: tflint --version

    - name: Init TFlint 
      run: tflint --init 

    - name: Run TFLint
      run: tflint -f compact 

    - name: Terraform plan
      run: terraform plan -var-file=enviroment/prod.tfvars
















