name: terraform-check


on: push

jobs: 
terraform-check: 
runs-on: ubuntu-latest 

steps: 
- name: Checkout repository 
uses: actions/checkout@v2 

- name: Configure AWS credentials 
users: aws-actions/configure-aws-credentials@v1
with: 
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: ap-southeast-1

- name: Set up Terraform 
uses: hashicorp/setup-terraform@v1

- name: Initialize Terraform 
run: terraform init 

- name: Terraform prettify 
run: terraform fmt 

-name: Terraform validate 
run: terraform validate 

- uses: terraform-linters/setup-tflint@v3
with: 
tflint_version: latest 

-name: Show version 
run-tflint --version 

-name: Init TFlint 
run: tflint -init 

-name: Run TFLint
run: tflint - f compact 

- name: Terraform plan
run: terraform plan -var-file=enviroment/prod.tfvars